### ISSUE TITLE
Set Date Taken for videos

### ISSUE THREAD

**Issue by jamborta** [trickortweak/flickr-uploader#65]
Do you think it is possible to update date taken for videos using metadata or the date of the file? It seems that flickr just sets the date to the date the video was uploaded.

**Comment by jamborta** [comment]
@oPromessa thanks that is almost done:

`                     import mimetypes
                    import time
                    filetype = mimetypes.guess_type(file)
                    if 'video' in filetype[0]:
                        video_date = time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(last_modified))
                        try:
                            res_set_date = flick.photos_set_dates(file_id, video_date)
                            if res_set_date['stat'] == 'ok':
                                print("Set date ok")
                        except (IOError, ValueError, httplib.HTTPException):
                            print(str(sys.exc_info()))
                            print("Error setting date")
                        if res_set_date['stat'] != 'ok':
                            raise IOError(res_set_date)
                        print("Successfully set date for pic number: " + str(file_id))`

`    def photos_set_dates(self, photo_id, datetxt):
        data = {
            "auth_token": str(self.token),
            "perms": str(self.perms),
            "format": "json",
            "nojsoncallback": "1",
            "method": "flickr.photos.setDates",
            "photo_id": str(photo_id),
            "date_taken": str(datetxt)
        }
        url = self.urlGen(api.rest, data, self.signCall(data))
        return self.getResponse(url)`

**Comment by ze6killer** [comment]
Hello,

I stumbled on this thread and would be quite interested in knowing what you did in the end.
Concretely: I am transcoding a lot of my videos from .MTS to .mov when they keep being listed as 'bad files'
Which of the exif metadata fields should I change for Flickr to have the correct 'Date Taken' ?


Ze

**Comment by oPromessa** [comment]
@ze6killer I've incorporated this code into updated tool at [flickr-uploader](github.com/oPromessa/flickr-uploader) and it **updates on Flickr the video date taken based on last_modified time of file**.

To adjust the last_modified time of a file you can resort to:
* the `touch` command on Linux 
* or make use of the exiftool (once installed)

### touch comand
Use the touch command and specify the date in the format `YYYYMMDDhhmm.SS`. Check out [this link on Changing a file's “Date Created” and “Last Modified” attributes](https://unix.stackexchange.com/questions/118577/changing-a-files-date-created-and-last-modified-attributes-to-another-file)
```bash
$ touch -a -m -t 201512180130.09 fileName.ext
```
### exiftool
Do check the exiftool options. This command sets the DateTimeOriginal (EXIF) date time but also Creation and modified date. 
* **Careful on how you use option** `-overwrite_original_in_place` which replaces the original file. remove it and exiftool will save the original. Use with care once you get the grip of things.
* option -d defines the format in which you specify the date/time. you can change it.
```bash
$ exiftool -d "%Y:%d:%m %H:%M:%S" -overwrite_original_in_place -fileOrder DateTimeOriginal -DateTimeOriginal="2015:12:21 01:30:09" -CreateDate="2015:12:21 01:30:09" -FileModifyDate="2015:12:21 01:30:09" -v filename.ext
```
* Final note: I have a few functions defined in bash so that I can easily list and set a few things on EXIF and dates. Will try to share them later on.

**Comment by oPromessa** [comment]
Here's the link to a [Gist with a few of the exiftool bash wrapper functions I use!](https://gist.github.com/oPromessa/059766e466df88383493f40a261e8391)

**Comment by ze6killer** [comment]
Well, actually I had tried with exiftool already but when I edit DateTimeOriginal, MediaCreateDate, FileModifyDate or CreateDate, Flickr still seems not to get the correct date for the file...

Does this come from how the script uploads the files or Flickr itself?

**Comment by oPromessa** [comment]
Flickr does not take into account the date/time for videos.
So the script takes the file modify date/time and updates it in Flickr. You should see output messages in uploadr.out like below.
Even if the video is already uploaded, after you run `exiftool` on it, it should update it on the next run.
Anyhow best if you try out with a new video and **make sure** the date/time update works (as per below output) or if there is any kind of error.
```
[441][2018.10.17 00:12:40]:[6526       ][PRINT   ]:[uploadr]  Uploading file:[tests/Test Photo Library/Videos Vários/Video01.MP4] On Album:[Videos Vários]...
[441][2018.10.17 00:12:44]:[6526       ][PRINT   ]:[uploadr]   Uploaded file:[tests/Test Photo Library/Videos Vários/Video01.MP4] ID=[44459671875]. Check for duplicates/wrong checksum...
[441][2018.10.17 00:12:44]:[6526       ][PRINT   ]:[uploadr] Successful file:[tests/Test Photo Library/Videos Vários/Video01.MP4]
[441][2018.10.17 00:12:44]:[6526       ][PRINT   ]:[uploadr]    Setting Date:[2018-10-17 00:12:12] for file:[tests/Test Photo Library/Videos Vários/Video01.MP4] Id=[44459671875]
[441][2018.10.17 00:12:44]:[6526       ][PRINT   ]:[uploadr] Successful date:[2018-10-17 00:12:12] for file:[tests/Test Photo Library/Videos Vários/Video01.MP4]
```

**Comment by oPromessa** [comment]
I'm closing this topic. @ze6killer and @jamborta let us keno if you have further queries.
