### ISSUE TITLE
Checksum tags

### ISSUE THREAD

**Issue by Gazz1e** [trickortweak/flickr-uploader#84]
Hi. Many thanks for writing this script. It has allowed me to upload my photo collection just by running it on my wdmycloud device. 

One issue I have with it (or maybe it's flickr) is that I have thousands of checksum tags. Each photo has it's own tag. I expect the script uses these checksums to determine what has and hasn't been uploaded. 

Couple of questions...

1) how can I delete these 1000s of tags? I don't need to check that files exist, as the directory I upload from only contains new photos. 

2) how can I stop additional checksum tags being created?

 Many thanks.

**Comment by oPromessa** [comment]
Hi Gazz'le,

Yes, those tags are used to sync the flickr-uploader database with flickr photos so that it can track, update and delete photos as required.

To disable you'd have to dwell a bit into the code.... with the caveat that it may defeat the purpose of this tool's functionality.

Sorry not to be of more help.

Thanks!

**Comment by oPromessa** [comment]
This fork [flickr-uploader](https://github.com/oPromessa/flickr-uploader) / also available [on pypi.org also](https://pypi.org/project/flickr-uploader/) is now being actively maintained and provides more extended features. Take a look at it.

The tags `checksum` continue to be used for control.

Closing this topic. @Gazz1e , let us know in case you have further queries.
