### ISSUE TITLE
move database to new location 

### ISSUE THREAD

**Issue by haphaeu** [trickortweak/flickr-uploader#85]
Hi,

Run out of space in the drive were the database was and had to move everything to a new location.

Is there an easy way to update the location of the database in the script? When I dry run the script in the new location it detects all files as "new" and would try to re-upload them all.

Thanks!

**Comment by oPromessa** [comment]
Hmmm. You ran out of space on the actual database folder and on the folder which contains the pictures.

Don't quite know if your issue is not finding the database file or not finding the pictures....

 I'd say the tool looks for the database in the current folder... so it should find it just fine... on the other hand it may not find the pictures as it may be using some relative path (which now fails as you moved the database/tool). 

If this is he case and, as I did not have a chance to check the actual code or test it, here goes a couple of options/suggestions:
1. (Simpler) simply create a symbolic link from the old location to the new one (of the database or the pictures... whichever is your problem). It will trick the tool to find the pictures in the "same old place". 
2. Change the config file (of course) and update the actual pictures location in the database itself via SQLite3... do MAKE a backup copy of the database. 

Hope it helps.

**Comment by oPromessa** [comment]
Dear haphaeu,

I have now checked the code:
1. It is confirmed the database file (named flickrdb by default) is defined within uploadr.ini under configuration value DB_PATH. My uploadr.ini file contains...
```
################################################################################
#   File we keep the history of uploaded files in.
################################################################################
DB_PATH = os.path.join(os.path.dirname(sys.argv[0]), "flickrdb")

```

2. I've ran "sqlit3 flickrdb" and checked that the pictures filenames are recorded as full pathnames... you can run this quick instruction within nsqlite3: 
` select * from files limit 10;`

3. So I don't exactly know what is the problem your facing. Anyhow the symbolic link should fix it. If not please post some more details...

Good luck!

**Comment by haphaeu** [comment]
Hi! Thank you for the help! 
The symbolic link solution sounds promising, I'll give it a try as soon as I can and let you know.

To detail my problem a bit more: I run out of space in the drive where I had my pictures. Then I moved (copied actually) all the pictures to a new location and updated the script DB_PATH pointing to the new location with exactly the same files as the old location. The problem then, as you've mention, since the full path is stored in the database, the script recognizes these pictures as "new" files.

But as mentioned before, I'll try a symbolic link pointing virtually to the "same old place" and see what happens ;)

Cheers

**Comment by haphaeu** [comment]
Hi again,
indeed creating a symbolic link worked like a charm. 
Thanks for the help!
