### ISSUE TITLE
Move files once complete

### ISSUE THREAD

**Issue by nb292** [trickortweak/flickr-uploader#88]
Thank you for this script been using it for years, and have uploaded over 80000 images. With the new addition of Synology's moments app. 

I'd like to see if there could be an option for the script to photos from vol1/photos to vol1/home/drive/moments once the upload is complete?

**Comment by oPromessa** [comment]
Hmmm. I’ve also used for a long time and I had to fork it (oPromessa/Flickr-uploads) in order to be able to use the new authentication method of Flickr (this version continues to work with currently authenticated users but is not capable of setting up new connections) and include a few more features.

(Sorry for the rambling)

To your point  on Moments app (have not yet tried it so take this notes under that assumption) it seems it uses another folder (moments) distinct from the PhtoAlbum folder (photo). 

If one moves the vol1/photo folder, the next time you run Flickr-uploadr it won’t be able to sync with Flickr any changes  you might have on vol1/photo. 

Another option could be to simply create a symbolic link (ln -s) from moments folder into vol1/photo.  Don’t quite know how moments will behave and if it will wreck the photo station app and it’s indexing. 

All the best.

**Comment by oPromessa** [comment]
I've been looking around at the new packages launched by Synology for Momens and Drive. Still did not installed it.
- Found an article on Synology to [move the files from PhotoStation into Moments](https://www.synology.com/en-global/knowledgebase/DSM/tutorial/Multimedia/How_to_move_or_copy_photos_from_Photo_Station_to_Moments) which you can use to move from /vol1/photo to /vol1/moments
- **IF** Synology Moments uses files from a folder structure... I think you can simply have flickr-uploadr to use /vol1/moments folder, once you moved your library from /vol1/photo into /vol1/moments

**Comment by oPromessa** [comment]
Well... this topic should probably be covered on the [Synology forum for Moments](https://forum.synology.com/enu/viewforum.php?f=290).

Take a look in particular to this tweak... [Moments beta - what about my existing folder of photos?](https://forum.synology.com/enu/viewtopic.php?f=290&t=136691&start=15#p509385)

**Comment by oPromessa** [comment]
I'm closing this topic due to lack of activity. @nb292 let us know should you have any further queries.
